"""Personal portfolio profile based on the user's recent holdings screenshot.

The balances and snapshot values are a recent approximation, not a live exchange
connection. Live values are estimated from current market prices whenever data
is available.
"""

PROFILE_STATUS = "Recent snapshot — balances can be refined later"
SNAPSHOT_CURRENCY = "AUD"
SNAPSHOT_TOTAL_AUD = 28043.68

PORTFOLIO_PROFILE = (
    {
        "id": "bitcoin",
        "name": "Bitcoin",
        "symbol": "BTC",
        "balance": 0.15819773,
        "snapshot_value_aud": 15031.19,
        "priority": 1,
        "group": "Foundation",
        "conviction": "Core",
        "narrative": "Store of value and market anchor",
    },
    {
        "id": "solana",
        "name": "Solana",
        "symbol": "SOL",
        "balance": 73.13710465,
        "snapshot_value_aud": 8417.45,
        "priority": 1,
        "group": "Foundation",
        "conviction": "Core",
        "narrative": "High-throughput Layer 1",
    },
    {
        "id": "avalanche-2",
        "name": "Avalanche",
        "symbol": "AVAX",
        "balance": 155.5786594,
        "snapshot_value_aud": 1516.42,
        "priority": 2,
        "group": "High conviction",
        "conviction": "High",
        "narrative": "Layer 1 and institutional subnets",
    },
    {
        "id": "polygon-ecosystem-token",
        "name": "Polygon Ecosystem Token",
        "symbol": "POL",
        "balance": 5744.900489,
        "snapshot_value_aud": 681.25,
        "priority": 2,
        "group": "High conviction",
        "conviction": "High",
        "narrative": "Ethereum scaling",
    },
    {
        "id": "polkadot",
        "name": "Polkadot",
        "symbol": "DOT",
        "balance": 415.2054283,
        "snapshot_value_aud": 516.00,
        "priority": 2,
        "group": "High conviction",
        "conviction": "High",
        "narrative": "Interoperability",
    },
    {
        "id": "zilliqa",
        "name": "Zilliqa",
        "symbol": "ZIL",
        "balance": 131037.5626,
        "snapshot_value_aud": 490.28,
        "priority": 2,
        "group": "High conviction",
        "conviction": "High",
        "narrative": "Layer 1",
    },
    {
        "id": "coti",
        "name": "COTI",
        "symbol": "COTI",
        "balance": 28002.75115,
        "snapshot_value_aud": 312.26,
        "priority": 2,
        "group": "High conviction",
        "conviction": "High",
        "narrative": "Privacy infrastructure",
    },
    {
        "id": "near",
        "name": "NEAR Protocol",
        "symbol": "NEAR",
        "balance": 98.89177795,
        "snapshot_value_aud": 296.00,
        "priority": 2,
        "group": "Growth position",
        "conviction": "Medium",
        "narrative": "AI and chain abstraction",
    },
    {
        "id": "sui",
        "name": "Sui",
        "symbol": "SUI",
        "balance": 160.3562903,
        "snapshot_value_aud": 181.71,
        "priority": 2,
        "group": "Growth position",
        "conviction": "Medium",
        "narrative": "High-performance Layer 1",
    },
    {
        "id": "superfarm",
        "name": "SuperVerse",
        "symbol": "SUPER",
        "balance": 1362.059053,
        "snapshot_value_aud": 175.47,
        "priority": 2,
        "group": "Growth position",
        "conviction": "Medium",
        "narrative": "Gaming ecosystem",
    },
    {
        "id": "sonic-3",
        "name": "Sonic",
        "symbol": "S",
        "balance": 4190.378059,
        "snapshot_value_aud": 153.28,
        "priority": 2,
        "group": "Growth position",
        "conviction": "Medium",
        "narrative": "Layer 1 and DeFi",
    },
    {
        "id": "aioz-network",
        "name": "AIOZ Network",
        "symbol": "AIOZ",
        "balance": 1553.802358,
        "snapshot_value_aud": 114.87,
        "priority": 2,
        "group": "Growth position",
        "conviction": "Medium",
        "narrative": "DePIN and media",
    },
    {
        "id": "filecoin",
        "name": "Filecoin",
        "symbol": "FIL",
        "balance": 84.29623079,
        "snapshot_value_aud": 91.77,
        "priority": 2,
        "group": "Growth position",
        "conviction": "Medium",
        "narrative": "Decentralised storage",
    },
    {
        "id": "sei-network",
        "name": "Sei",
        "symbol": "SEI",
        "balance": 948.5449288,
        "snapshot_value_aud": 65.73,
        "priority": 2,
        "group": "Growth position",
        "conviction": "Medium",
        "narrative": "Trading-focused Layer 1",
    },
)

PROFILE_BY_SYMBOL = {asset["symbol"]: asset for asset in PORTFOLIO_PROFILE}
