PORTFOLIO = (
    {
        "id": "ethereum",
        "name": "Ethereum",
        "symbol": "ETH",
        "weight": 35.0,
        "score": 96,
        "risk": "MEDIUM",
        "narrative": "Core infrastructure",
    },
    {
        "id": "chainlink",
        "name": "Chainlink",
        "symbol": "LINK",
        "weight": 20.0,
        "score": 89,
        "risk": "MEDIUM",
        "narrative": "Oracle and tokenisation",
    },
    {
        "id": "ondo-finance",
        "name": "Ondo Finance",
        "symbol": "ONDO",
        "weight": 15.0,
        "score": 76,
        "risk": "MEDIUM",
        "narrative": "Real-world assets",
    },
    {
        "id": "hyperliquid",
        "name": "Hyperliquid",
        "symbol": "HYPE",
        "weight": 15.0,
        "score": 82,
        "risk": "MEDIUM",
        "narrative": "Decentralised trading",
    },
    {
        "id": "coti",
        "name": "COTI",
        "symbol": "COTI",
        "weight": 10.0,
        "score": 58,
        "risk": "MEDIUM",
        "narrative": "Privacy infrastructure",
    },
    {
        "id": "zilliqa",
        "name": "Zilliqa",
        "symbol": "ZIL",
        "weight": 5.0,
        "score": 45,
        "risk": "HIGH",
        "narrative": "Layer 1",
    },
)
